name: Manubot
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  manubot:
    name: Manubot
    runs-on: ubuntu-latest
    env:
      GITHUB_PULL_REQUEST_SHA: ${{ github.event.pull_request.head.sha }}
    steps:
      - name: Set Environment Variables
        run: |
          TRIGGERING_SHA=${GITHUB_PULL_REQUEST_SHA:-$GITHUB_SHA}
          TRIGGERING_SHA_7=${TRIGGERING_SHA::7}
          echo "::set-env name=TRIGGERING_SHA_7::$TRIGGERING_SHA_7"
          echo "TRIGGERING_SHA: $TRIGGERING_SHA"
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          # fetch entire commit history to support get_rootstock_commit
          fetch-depth: 0
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ci/cache
          key: ci-cache-${{ github.ref }}
          restore-keys: |
            ci-cache-refs/heads/master
      - name: Install Environment
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: manubot
          environment-file: build/environment.yml
          auto-activate-base: false
          miniconda-version: 'latest'
      - name: Build Manuscript
        shell: bash --login {0}
        run: bash build/build.sh
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: manuscript-${{ github.run_id }}-${{ env.TRIGGERING_SHA_7 }}
          path: output
      - name: Create Artifact Comment
        run: |
          ARTIFACT_MESSAGE="GitHub Actions build 123456 for commit abcd123 by XXXXX is now complete. The rendered manuscript from this build is temporarily available."
          echo "::set-env name=ARTIFACT_MESSAGE::$ARTIFACT_MESSAGE"
      - name: Comment on Pull Request
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{ env.ARTIFACT_MESSAGE }}'
            })
      - name: Deploy Manuscript
        if: github.ref == 'refs/heads/master' && github.event_name == 'push' && !github.event.repository.fork
        env:
          MANUBOT_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MANUBOT_SSH_PRIVATE_KEY: ${{ secrets.MANUBOT_SSH_PRIVATE_KEY }}
          CI_BUILD_WEB_URL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks
          CI_JOB_WEB_URL: https://github.com/${{ github.repository }}/runs/${{ github.run_id }}
        shell: bash --login {0}
        run: bash ci/deploy.sh
